### ISSUE TITLE
Cannery doesn't like cans close-ish to switch?

### ISSUE THREAD

**Issue by blank3times** [RHeavenStudio/HeavenStudio#740]
### Describe the bug

In commemoration of my first few bug reports being pretty much just like this approximately one year ago, here's another example of "stuff stops working sometimes but not other times"! It's deterministic but I don't know why...

This was been a problem only on offbeats, and when there's more than one of them, but now looking it has happened to an onbeat that was really close to the switch game (0.25 after of course), but then other times it works when it's before the switch..?

### How to reproduce the bug?

Spam cannery with offbeats and proximities to the switch? I have no idea. You can try the .riq and move stuff around from there

### Screenshots/Videos

https://github.com/RHeavenStudio/HeavenStudio/assets/105398129/f8947751-3121-44cb-89c3-4292c0867034

### RIQ file

[remix_lizards - Copy.riq.zip](https://github.com/RHeavenStudio/HeavenStudio/files/14478610/remix_lizards.-.Copy.riq.zip)

**Comment by blank3times** [comment]
Happy belated anniversary, me

Happy to chat to figure this out

**Comment by blank3times** [comment]
I'll test the hotfix soon :)

**Comment by AstrlJelly** [comment]
yeah the hotfix should fix this. was a matter of not checking stuff correctly

**Comment by blank3times** [comment]
You can close it then, or I can do it myself too later ^-^

**Comment by blank3times** [comment]
Still doesn't work for me on what I think should be the nightly, what's the current build number?

**Comment by RaffyTaffy14** [comment]
idk how it was before but now it needs 2 whole beats inbetween the first cue and the game switch
